version: "3.8"

services:      
  keycloak-db:
    container_name: keycloak-db
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    stdin_open: false
    tty: false
    ports:
      - 4406:3306

    env_file:
     - .env.keycloak
    volumes:
      - ../../../keycloak-db-data:/var/lib/mysql
    networks:
      - keycloak-net
    healthcheck:
        test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
        timeout: 20s
        retries: 10


  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.0      
    networks:
    - keycloak-net
    volumes:
      - .\certs-localhost:/srv/certs
    env_file:
     - .env.keycloak
    environment:
      KC_DB_URL_PORT: 3306
    ports:
      - 8443:8443
    command: start
    depends_on:
      keycloak-db:
        condition: service_healthy
        
networks:
  keycloak-net:
  
