version: "3.8"

services:      
  keycloak-db:
    container_name: keycloak-db
    build:
      context: .
      dockerfile: keycloak-db.Dockerfile      
    image: keycloak-db:0.1 
    stdin_open: false
    tty: false
    ports:
      - 4406:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=keycloakR007*
      - MYSQL_DATABASE=keycloak_db
      - MYSQL_USER=keycloak-db-user
      - MYSQL_PASSWORD=SecretP^55word*9911
    volumes:
      - G:\dev\java-projects\keycloak-db-data:/var/lib/mysql
    networks:
      - keycloak-net
    healthcheck:
        test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
        timeout: 20s
        retries: 10

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.0      
    networks:
    - keycloak-net
    volumes:
      - .\certs-localhost:/srv/certs
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak-db-user
      KC_DB_PASSWORD: SecretP^55word*9911
      KC_HTTPS_CERTIFICATE_FILE: /srv/certs/localhost.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /srv/certs/localhost.key
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. 
        # The parameter below is just an example, and it shouldn't be used in production without knowledge. 
        # It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8443:8443
    command: start
    depends_on:
      keycloak-db:
        condition: service_healthy
        
networks:
  keycloak-net: