version: "3.8"
services:
  keycloak-db:
    container_name: keycloak-db
    build: "."
    image: keycloak-db:0.1 
    stdin_open: false
    tty: false
    ports:
      - 4406:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=keycloakR007*
      - MYSQL_DATABASE=keycloak_db
      - MYSQL_USER=keycloak-db-user
      - MYSQL_PASSWORD=SecretP^55word*9911
    volumes:
      - G:\dev\java-projects\keycloak-db-data:/var/lib/mysql
    networks:
      - keycloak-net

  keycloak-db-cli:
    container_name: keycloak-db-cli
    image: "imega/mysql-client:latest"
    stdin_open: true
    tty: true
    networks:
      - keycloak-net
    depends_on:
      - keycloak-db
    command:  mysql -u keycloak-db-user -pSecretP^55word*9911 --protocol=TCP --host=keycloak-db --port=3306
    
networks:
  keycloak-net: