name: Build-Test-Publish

on:

 workflow_dispatch: 

 pull_request:
    branches: [ main ]
    types: [closed]


jobs:
  build-test-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2 
    
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
            
    - name: Upload hello-world-jar
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-jar
        path: target/hello-world*.jar
